// pages
export 'auth/pages/forgot_password_page.dart';
export 'auth/pages/login_page.dart';
export 'auth/pages/register_page.dart';
export 'main/widgets/collections_content.dart';
export 'about/about_page.dart';
export 'main/widgets/profile_content.dart';
export 'main/widgets/home_content.dart';
export 'settings/settings_page.dart';
export 'main/main_page.dart';
export 'profile/edit_profile_page.dart';
