name: tireinspectorai_app
description: "TireInspectorAI is an innovative mobile application designed to inspect and analyze the condition of tires using advanced artificial intelligence algorithms. This app helps users ensure their vehicle's tires are in optimal condition for safe driving."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.3.0
  firebase_ml_model_downloader: ^0.3.1+2
  tflite_flutter: ^0.11.0
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.7
  intl: ^0.19.0
  google_sign_in: ^6.2.1
  firebase_auth: ^5.3.0
  json_annotation: ^4.9.0
  firebase_cloud_firestore: ^5.4.0
  package_info_plus: ^8.0.2
  shared_preferences: ^2.3.2
  firebase_storage: ^12.3.1
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  logger: ^2.4.0
  image: ^4.2.0

dependency_overrides:
  web: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.12
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: "^0.14.0"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/images/about/

flutter_native_splash:
  android: true
  ios: true

  background_image: assets/images/splash/background.png
  image: assets/images/splash/logo.png
  branding: assets/images/splash/branding.png

  android_12:
    color: "#d4e4ed"
    image: assets/images/splash/android_logo.png
    branding: assets/images/splash/android_branding.png    

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icons/app-icon.png"
